# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W7ehr5NhWEkirfsdQwLCJ0kRLjVsKOjS
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load sales data
file_path = "/content/sales_data.csv"  # Update this path as needed
sales_data = pd.read_csv(file_path)

# Convert 'Date' column to datetime if it exists
if 'Date' in sales_data.columns:
    sales_data['Date'] = pd.to_datetime(sales_data['Date'])

# Correlation Heatmap (only for numeric columns)
plt.figure(figsize=(8, 6))

# Selecting only numeric columns
numeric_data = sales_data.select_dtypes(include=['number'])

if not numeric_data.empty:  # Ensure at least one numeric column exists
    sns.heatmap(numeric_data.corr(), annot=True, cmap="coolwarm", fmt=".2f", linewidths=0.5)
    plt.title("Feature Correlation Heatmap", fontsize=14)
    plt.show()
else:
    print("No numeric columns available for correlation heatmap.")

import pandas as pd
import matplotlib.pyplot as plt

# Sample Sales Data (You can replace it with a CSV file or actual dataset)
data = {
    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
    'Sales': [1000, 1500, 1200, 1700, 1600, 1800],  # Monthly sales in dollars
    'Product_A': [400, 600, 500, 800, 750, 900],    # Sales for Product A
    'Product_B': [600, 900, 700, 900, 850, 900],    # Sales for Product B
    'Region': ['North', 'South', 'East', 'West', 'North', 'South']
}

# Convert dictionary to DataFrame
df = pd.DataFrame(data)

# 1. Line Chart - Monthly Sales Trend
plt.figure(figsize=(8, 5))
plt.plot(df['Month'], df['Sales'], marker='o', linestyle='-', color='b', label="Total Sales")
plt.xlabel('Month')
plt.ylabel('Sales ($)')
plt.title('Monthly Sales Trend')
plt.legend()
plt.grid(True)
plt.show()

# 2. Bar Chart - Sales by Product
plt.figure(figsize=(8, 5))
plt.bar(df['Month'], df['Product_A'], label='Product A', color='skyblue')
plt.bar(df['Month'], df['Product_B'], bottom=df['Product_A'], label='Product B', color='orange')
plt.xlabel('Month')
plt.ylabel('Sales ($)')
plt.title('Product-wise Sales Distribution')
plt.legend()
plt.show()

# 3. Pie Chart - Regional Sales Contribution
region_counts = df['Region'].value_counts()
plt.figure(figsize=(6, 6))
plt.pie(region_counts, labels=region_counts.index, autopct='%1.1f%%', colors=['red', 'green', 'blue', 'yellow'])
plt.title('Sales Distribution by Region')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Sample Sales Data (You can replace it with a CSV file or actual dataset)
data = {
    'Month': ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun'],
    'Sales': [1000, 1500, 1200, 1700, 1600, 1800],  # Monthly sales in dollars
    'Product_A': [400, 600, 500, 800, 750, 900],    # Sales for Product A
    'Product_B': [600, 900, 700, 900, 850, 900],    # Sales for Product B
    'Region': ['North', 'South', 'East', 'West', 'North', 'South']
}

# Convert dictionary to DataFrame
df = pd.DataFrame(data)

# 1. Line Chart - Monthly Sales Trend
plt.figure(figsize=(8, 5))
plt.plot(df['Month'], df['Sales'], marker='o', linestyle='-', color='b', label="Total Sales")
plt.xlabel('Month')
plt.ylabel('Sales ($)')
plt.title('Monthly Sales Trend')
plt.legend()
plt.grid(True)
plt.show()

# 2. Bar Chart - Sales by Product
plt.figure(figsize=(8, 5))
plt.bar(df['Month'], df['Product_A'], label='Product A', color='skyblue')
plt.bar(df['Month'], df['Product_B'], bottom=df['Product_A'], label='Product B', color='orange')
plt.xlabel('Month')
plt.ylabel('Sales ($)')
plt.title('Product-wise Sales Distribution')
plt.legend()
plt.show()

# 3. Pie Chart - Regional Sales Contribution
region_counts = df['Region'].value_counts()
plt.figure(figsize=(6, 6))
plt.pie(region_counts, labels=region_counts.index, autopct='%1.1f%%', colors=['red', 'green', 'blue', 'yellow'])
plt.title('Sales Distribution by Region')
plt.show()